# Generated by Django 4.1.1 on 2022-09-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='mdkkdm', upload_to='galary'),
            preserve_default=False,
        ),
    ]
